version: 2.2.0.{build}
image: Visual Studio 2017

build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild /restore /m /p:Configuration=Release /clp:v=m TaglibSharp.sln /bl /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: msbuild.binlog
  name: MSBuild Log
- path: src/TaglibSharp/bin/Release/*.nupkg
  name: nuget package

deploy:
- provider: NuGet
  api_key:
    secure: J/zTFDbBs9ZTzStL+eqWi1yRRe5cofenCW9v8Tjz0p56OggFbsKNzqio0A4wH5cV

on_failure:
- appveyor PushArtifact msbuild.binlog
